tap "homebrew/bundle"
tap "simonbs/dependency-graph", "https://github.com/simonbs/dependency-graph.git"

brew "cloc"
brew "ffmpeg"
brew "gnupg"
brew "graphviz"
brew "irssi"
brew "openssl@1.1"
brew "pinentry-mac"
brew "python@3.11"
brew "simonbs/dependency-graph/dependency-graph"
brew "wget"
brew "xcodegen"
brew "yt-dlp"
