tap "simonbs/dependency-graph", "https://github.com/simonbs/dependency-graph.git"
brew "cloc"
brew "ffmpeg"
brew "gnupg"
brew "graphviz"
brew "helix"
brew "irssi"
brew "pinentry-mac"
brew "python@3.11"
brew "wget"
brew "xcodegen"
brew "yt-dlp"
brew "simonbs/dependency-graph/dependency-graph"
